class Commands:
    LINE_FEED = b'\x0a'
    CARRIAGE_RETURN = b'\x0d'
    INIT = b'\x1b\x40'
    SELECT_PRINTER_MODE = b'\x1b\x21'
    UNDERLINE_MODE = b'\x1b\x2d'
    ITALIC_MODE = b'\x1b\x34'
    EMPHASIS_MODE = b'\x1b\x45'
    SELECT_CHAR_FONT = b'\x1b\x4d'
    SELECT_CHAR_SIZE = b'\x1d\x21'
    REVERSE_PRINT_MODE = b'\x1d\x42'
    SELECT_JUSTIFICATION = b'\x1b\x61'
    PARTIAL_CUT = b'\x1b\x69'
    PRINTER_ID = b'\x1d\x49'
    RASTER_IMAGE = b'\x1d\x76\x30'

    # Additional
    ON = b'\x01'
    OFF = b'\x00'

class PhoenixCommands(Commands):
    SELECT_FONT_A = b'\x1b\x50'
    SELECT_FONT_B = b'\x1b\x54'
    SELECT_FONT_C = b'\x1b\x55'
    PAPER_STATUS = b'\x1b\x76'
    PRINT_N_FEED_PAPER_N_LINES = b'\x1b\x64'
    PRINT_N_FEED_PAPER = b'\x1b\x4a'
    REAL_TIME_STATUS = b'\x10\x04'
    DOUBLE_STRIKE_MODE = b'\x1b\x47'
    SELECT_CUT_MODE_AND_CUT_PAPER = b'\x1d\x56'
    FULL_CUT = b'\x1b\x6d'
    TOGGLE_AUTO_CUT = b'\x1c\x7d\x60'
    DYNAMIC_2D_BARCODE = b'\x1d\x28\x6b'
    PRINT_REAL_TIME_CLOCK = b'\x1c\x7d\x70'

    RT_PRINTER = b'\x01'
    RT_OFFLINE = b'\x02'
    RT_ERROR = b'\x03'
    RT_PAPER = b'\x04'

    # Actions
    TEST_COIN_IN = b'\x60'
    TEST_NOTE_IN = b'\x61'
    PRINT_RTC = b'\x1c\x7d\x70'

class RelianceCommands(Commands):
    HORIZONTAL_TAB = b'\x09'
    FORM_FEED = b'\x0c'
    CANCEL_CURRENT_LINE = b'\x18'
    ABSOLUTE_PRINT_POSITION = b'\x1b\x24'
    RELATIVE_PRINT_POSITION = b'\x1b\x5c'
    REAl_TIME_STATUS = b'\x10\x04'
    ROTATE_90_DEGREES = b'\x1b\x56'
    SELECT_CHAR_PAGE = b'\x1b\x74'
    UPSIDE_DOWN_MODE = b'\x1b\x7b'
    SET_CPI_MODE = b'\x1b\xc1'
    SELECT_CODEPAGE = b'\x1c\x7d\x26'
    RIGHT_SIDE_CHAR_SPACING = b'\x1b\x20'
    LINE_SPACING = b'\x1b\x33'
    SELECT_1_6_INCH_LINE_SPACING = b'\x1b\x32'
    SELECT_1_8_INCH_LINE_SPACING = b'\x1b\x30'
    LEFT_MARGIN = b'\x1d\x4c'
    MOTION_UNIT = b'\x1d\x50'
    PRINT_AREA_WIDTH = b'\x1d\x57'
    SELECT_PAGE_MODE = b'\x1b\x4c'
    SELECT_STANDARD_MODE = b'\x1b\x53'
    EJECTOR = b'\x1d\x65'
    TRANSMIT_STATUS = b'\x1d\x72'
    BARCODE_GENERATOR_2D = b'\x1c\x7d\x25'
    SET_2D_BARCODE_SIZE = b'\x1c\x7d\x74'
    BARCODE_GENERATOR = b'\x1d\x6b'
    SET_1d_BARCODE_WIDTH_MULT = b'\x1d\x77'
    SET_1D_BARCODE_HEIGHT = b'\x1d\x68'
    SET_HRI_PRINTING_POSITION = b'\x1d\x48'
    SET_HRI_FONT = b'\x1d\x66'
    PRINT_GRAPHIC_BANK_LOGO = b'\x1b\xfa'
    PRINT_GRAPHIC_BANK_LOGO_SIMPLIFIED = b'\x1c\x79'